name: CI Docker Dev Environment
on: [push, pull_request]
jobs:
  build:
    name: Build and Test Docker Dev Environment (${{ matrix.os }} / JDK ${{ matrix.jdk }} / eXist-db ${{ matrix.exist-version }})
    strategy:
      fail-fast: true
      matrix:
        jdk: ['8']
        exist-version: ['6.1.0-SNAPSHOT']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ matrix.exist-version }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-${{ matrix.exist-version }}-maven
      - name: Maven Build
        run: mvn -V clean package
      - name: Start Docker Dev Environment
        run: mvn -Pdev -Dexist.version=${{ matrix.exist-version }} docker:start
      - name: Query Docker Dev Environment
        run: curl -vv "http://localhost:9090/exist/rest/db/?_query=system:get-version()"
      - name: Stop Docker Dev Environment
        run: mvn -Pdev -Dexist.version=${{ matrix.exist-version }} docker:stop
